# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_parameters.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(755, 566)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(260, 490, 451, 71))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 221, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_A1_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_A1_4.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_4.setObjectName("label_A1_4")
        self.gridLayout.addWidget(self.label_A1_4, 2, 4, 1, 1)
        self.label_A1_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_A1_8.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_8.setObjectName("label_A1_8")
        self.gridLayout.addWidget(self.label_A1_8, 4, 2, 1, 1)
        self.lineEditA2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditA2.setObjectName("lineEditA2")
        self.gridLayout.addWidget(self.lineEditA2, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEditA3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditA3.setObjectName("lineEditA3")
        self.gridLayout.addWidget(self.lineEditA3, 3, 2, 1, 1)
        self.label_A1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_A1.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1.setObjectName("label_A1")
        self.gridLayout.addWidget(self.label_A1, 0, 2, 1, 1)
        self.lineEditA1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditA1.setObjectName("lineEditA1")
        self.gridLayout.addWidget(self.lineEditA1, 1, 2, 1, 1)
        self.lineEditA4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditA4.setObjectName("lineEditA4")
        self.gridLayout.addWidget(self.lineEditA4, 2, 1, 1, 1)
        self.label_A1_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_A1_19.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_19.setObjectName("label_A1_19")
        self.gridLayout.addWidget(self.label_A1_19, 2, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(260, 40, 221, 181))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_A1_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_A1_3.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_3.setObjectName("label_A1_3")
        self.gridLayout_2.addWidget(self.label_A1_3, 0, 2, 1, 1)
        self.label_A1_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_A1_9.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_9.setObjectName("label_A1_9")
        self.gridLayout_2.addWidget(self.label_A1_9, 2, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEditB2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditB2.setObjectName("lineEditB2")
        self.gridLayout_2.addWidget(self.lineEditB2, 2, 3, 1, 1)
        self.lineEditB1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditB1.setObjectName("lineEditB1")
        self.gridLayout_2.addWidget(self.lineEditB1, 1, 2, 1, 1)
        self.lineEditB4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditB4.setObjectName("lineEditB4")
        self.gridLayout_2.addWidget(self.lineEditB4, 2, 1, 1, 1)
        self.lineEditB3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditB3.setObjectName("lineEditB3")
        self.gridLayout_2.addWidget(self.lineEditB3, 3, 2, 1, 1)
        self.label_A1_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_A1_15.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_15.setObjectName("label_A1_15")
        self.gridLayout_2.addWidget(self.label_A1_15, 4, 2, 1, 1)
        self.label_A1_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_A1_21.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_21.setObjectName("label_A1_21")
        self.gridLayout_2.addWidget(self.label_A1_21, 2, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(500, 40, 231, 181))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_A1_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_A1_11.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_11.setObjectName("label_A1_11")
        self.gridLayout_3.addWidget(self.label_A1_11, 2, 4, 1, 1)
        self.label_A1_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_A1_5.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_5.setObjectName("label_A1_5")
        self.gridLayout_3.addWidget(self.label_A1_5, 0, 2, 1, 1)
        self.lineEditC2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEditC2.setObjectName("lineEditC2")
        self.gridLayout_3.addWidget(self.lineEditC2, 2, 3, 1, 1)
        self.lineEditC1 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEditC1.setObjectName("lineEditC1")
        self.gridLayout_3.addWidget(self.lineEditC1, 1, 2, 1, 1)
        self.lineEditC3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEditC3.setObjectName("lineEditC3")
        self.gridLayout_3.addWidget(self.lineEditC3, 3, 2, 1, 1)
        self.lineEditC4 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEditC4.setObjectName("lineEditC4")
        self.gridLayout_3.addWidget(self.lineEditC4, 2, 1, 1, 1)
        self.label_A1_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_A1_17.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_17.setObjectName("label_A1_17")
        self.gridLayout_3.addWidget(self.label_A1_17, 4, 2, 1, 1)
        self.label_A1_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_A1_23.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_23.setObjectName("label_A1_23")
        self.gridLayout_3.addWidget(self.label_A1_23, 2, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(500, 290, 231, 171))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEditC3_Sen = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEditC3_Sen.setObjectName("lineEditC3_Sen")
        self.gridLayout_4.addWidget(self.lineEditC3_Sen, 3, 2, 1, 1)
        self.lineEditC1_Sen = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEditC1_Sen.setObjectName("lineEditC1_Sen")
        self.gridLayout_4.addWidget(self.lineEditC1_Sen, 1, 2, 1, 1)
        self.lineEditC4_Sen = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEditC4_Sen.setObjectName("lineEditC4_Sen")
        self.gridLayout_4.addWidget(self.lineEditC4_Sen, 2, 1, 1, 1)
        self.lineEditC2_Sen = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEditC2_Sen.setObjectName("lineEditC2_Sen")
        self.gridLayout_4.addWidget(self.lineEditC2_Sen, 2, 3, 1, 1)
        self.label_A1_6 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_A1_6.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_6.setObjectName("label_A1_6")
        self.gridLayout_4.addWidget(self.label_A1_6, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_A1_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_A1_12.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_12.setObjectName("label_A1_12")
        self.gridLayout_4.addWidget(self.label_A1_12, 2, 4, 1, 1)
        self.label_A1_18 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_A1_18.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_18.setObjectName("label_A1_18")
        self.gridLayout_4.addWidget(self.label_A1_18, 4, 2, 1, 1)
        self.label_A1_24 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_A1_24.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_24.setObjectName("label_A1_24")
        self.gridLayout_4.addWidget(self.label_A1_24, 2, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(260, 290, 221, 171))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEditB1_Sen = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEditB1_Sen.setObjectName("lineEditB1_Sen")
        self.gridLayout_5.addWidget(self.lineEditB1_Sen, 1, 2, 1, 1)
        self.lineEditB3_Sen = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEditB3_Sen.setObjectName("lineEditB3_Sen")
        self.gridLayout_5.addWidget(self.lineEditB3_Sen, 3, 2, 1, 1)
        self.lineEditB2_Sen = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEditB2_Sen.setObjectName("lineEditB2_Sen")
        self.gridLayout_5.addWidget(self.lineEditB2_Sen, 2, 3, 1, 1)
        self.lineEditB4_Sen = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEditB4_Sen.setObjectName("lineEditB4_Sen")
        self.gridLayout_5.addWidget(self.lineEditB4_Sen, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_A1_10 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_A1_10.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_10.setObjectName("label_A1_10")
        self.gridLayout_5.addWidget(self.label_A1_10, 2, 4, 1, 1)
        self.label_A1_16 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_A1_16.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_16.setObjectName("label_A1_16")
        self.gridLayout_5.addWidget(self.label_A1_16, 4, 2, 1, 1)
        self.label_A1_7 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_A1_7.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_7.setObjectName("label_A1_7")
        self.gridLayout_5.addWidget(self.label_A1_7, 0, 2, 1, 1)
        self.label_A1_22 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_A1_22.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_22.setObjectName("label_A1_22")
        self.gridLayout_5.addWidget(self.label_A1_22, 2, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(20, 290, 221, 171))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEditA3_Sen = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEditA3_Sen.setObjectName("lineEditA3_Sen")
        self.gridLayout_6.addWidget(self.lineEditA3_Sen, 3, 2, 1, 1)
        self.lineEditA2_Sen = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEditA2_Sen.setObjectName("lineEditA2_Sen")
        self.gridLayout_6.addWidget(self.lineEditA2_Sen, 2, 3, 1, 1)
        self.lineEditA1_Sen = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEditA1_Sen.setObjectName("lineEditA1_Sen")
        self.gridLayout_6.addWidget(self.lineEditA1_Sen, 1, 2, 1, 1)
        self.lineEditA4_Sen = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEditA4_Sen.setObjectName("lineEditA4_Sen")
        self.gridLayout_6.addWidget(self.lineEditA4_Sen, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_A1_2 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_A1_2.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_2.setObjectName("label_A1_2")
        self.gridLayout_6.addWidget(self.label_A1_2, 0, 2, 1, 1)
        self.label_A1_13 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_A1_13.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_13.setObjectName("label_A1_13")
        self.gridLayout_6.addWidget(self.label_A1_13, 4, 2, 1, 1)
        self.label_A1_14 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_A1_14.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_14.setObjectName("label_A1_14")
        self.gridLayout_6.addWidget(self.label_A1_14, 2, 4, 1, 1)
        self.label_A1_20 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_A1_20.setMaximumSize(QtCore.QSize(102, 30))
        self.label_A1_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A1_20.setObjectName("label_A1_20")
        self.gridLayout_6.addWidget(self.label_A1_20, 2, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 500, 491, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.lineEdit_all_Sen = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_all_Sen.setMaximumSize(QtCore.QSize(150, 30))
        self.lineEdit_all_Sen.setObjectName("lineEdit_all_Sen")
        self.horizontalLayout.addWidget(self.lineEdit_all_Sen)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 100))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 251, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 220, 271, 91))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "参数设置"))
        self.label_A1_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">2</span></p></body></html>"))
        self.label_A1_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">3</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">A</span></p></body></html>"))
        self.label_A1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">1</span></p></body></html>"))
        self.label_A1_19.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">4</span></p></body></html>"))
        self.label_A1_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">1</span></p></body></html>"))
        self.label_A1_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">2</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">B</span></p></body></html>"))
        self.label_A1_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">3</span></p></body></html>"))
        self.label_A1_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">4</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">C</span></p></body></html>"))
        self.label_A1_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">2</span></p></body></html>"))
        self.label_A1_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">1</span></p></body></html>"))
        self.label_A1_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">3</span></p></body></html>"))
        self.label_A1_23.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">4</span></p></body></html>"))
        self.label_A1_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">1</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">C</span></p></body></html>"))
        self.label_A1_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">2</span></p></body></html>"))
        self.label_A1_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">3</span></p></body></html>"))
        self.label_A1_24.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">4</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">B</span></p></body></html>"))
        self.label_A1_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">2</span></p></body></html>"))
        self.label_A1_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">3</span></p></body></html>"))
        self.label_A1_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">1</span></p></body></html>"))
        self.label_A1_22.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">4</span></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">A</span></p></body></html>"))
        self.label_A1_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">1</span></p></body></html>"))
        self.label_A1_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">3</span></p></body></html>"))
        self.label_A1_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">2</span></p></body></html>"))
        self.label_A1_20.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">4</span></p></body></html>"))
        self.checkBox.setText(_translate("Dialog", "统一设定灵敏值"))
        self.pushButton.setText(_translate("Dialog", "设定"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">通道的标定值</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">灵敏度设置</span></p></body></html>"))

