# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TZD.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1332, 652)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/logo.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 321, 511))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(-1, -1, 0, 10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_com = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_com.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_com.setObjectName("lineEdit_com")
        self.horizontalLayout.addWidget(self.lineEdit_com)
        self.btnSetParameters = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnSetParameters.setObjectName("btnSetParameters")
        self.horizontalLayout.addWidget(self.btnSetParameters)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_delete_force = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_delete_force.setObjectName("btn_delete_force")
        self.gridLayout_3.addWidget(self.btn_delete_force, 0, 1, 1, 1)
        self.btn_apply_force = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_apply_force.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.btn_apply_force.setObjectName("btn_apply_force")
        self.gridLayout_3.addWidget(self.btn_apply_force, 1, 0, 1, 1)
        self.btn_add_force = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_add_force.setObjectName("btn_add_force")
        self.gridLayout_3.addWidget(self.btn_add_force, 0, 0, 1, 1)
        self.btnEnd = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnEnd.setObjectName("btnEnd")
        self.gridLayout_3.addWidget(self.btnEnd, 1, 2, 1, 1)
        self.btnReceive = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnReceive.setObjectName("btnReceive")
        self.gridLayout_3.addWidget(self.btnReceive, 0, 2, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout_3.addWidget(self.btnSave, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.tableView_force = QtWidgets.QTableView(self.gridLayoutWidget_4)
        self.tableView_force.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tableView_force.setObjectName("tableView_force")
        self.gridLayout_4.addWidget(self.tableView_force, 1, 0, 1, 1)
        self.checkBox_twice = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_twice.setObjectName("checkBox_twice")
        self.gridLayout_4.addWidget(self.checkBox_twice, 3, 0, 1, 1)
        self.textBrowser_info = QtWidgets.QTextBrowser(Form)
        self.textBrowser_info.setGeometry(QtCore.QRect(20, 550, 1301, 71))
        self.textBrowser_info.setObjectName("textBrowser_info")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(366, 9, 951, 531))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget_strain = StrainPlotWidget(self.tab)
        self.widget_strain.setGeometry(QtCore.QRect(10, 0, 931, 491))
        self.widget_strain.setMinimumSize(QtCore.QSize(800, 0))
        self.widget_strain.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.widget_strain.setObjectName("widget_strain")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 921, 690))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(50, 30))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_A_A = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_A.setObjectName("lineEdit_A_A")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_A)
        self.lineEdit_A_A0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A0.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A0.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_A_A0.setObjectName("lineEdit_A_A0")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_A0)
        self.lineEdit_A_A1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A1.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_A1.setObjectName("lineEdit_A_A1")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_A1)
        self.lineEdit_A_A2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_A_A2.setObjectName("lineEdit_A_A2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_A2)
        self.lineEdit_A_A3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_A3.setObjectName("lineEdit_A_A3")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_A3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(50, 30))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_A_B = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_B.setObjectName("lineEdit_A_B")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_B)
        self.lineEdit_A_B0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B0.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B0.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_A_B0.setObjectName("lineEdit_A_B0")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_B0)
        self.lineEdit_A_B1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B1.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_B1.setObjectName("lineEdit_A_B1")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_B1)
        self.lineEdit_A_B2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B2.setObjectName("lineEdit_A_B2")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_B2)
        self.lineEdit_A_B3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_B3.setObjectName("lineEdit_A_B3")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_B3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(16, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(16, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.label_19)
        self.label_68 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_68.setObjectName("label_68")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_68)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_20)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(50, 30))
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_B_A = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_B_A.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_B_A.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_B_A.setObjectName("lineEdit_B_A")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_B_A)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_22)
        self.lineEdit_B_A0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_B_A0.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_B_A0.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_B_A0.setObjectName("lineEdit_B_A0")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lineEdit_B_A0)
        self.lineEdit_B_A1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_B_A1.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_B_A1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_B_A1.setObjectName("lineEdit_B_A1")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_B_A1)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_24)
        self.lineEdit_B_A2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_B_A2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_B_A2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_B_A2.setObjectName("lineEdit_B_A2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lineEdit_B_A2)
        self.lineEdit_B_A3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_B_A3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_B_A3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_B_A3.setObjectName("lineEdit_B_A3")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_B_A3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem9)
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_25)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(50, 30))
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_B_B = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_B_B.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_B_B.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_B_B.setObjectName("lineEdit_B_B")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEdit_B_B)
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.label_27)
        self.lineEdit_B_B0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_B_B0.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_B_B0.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_B_B0.setObjectName("lineEdit_B_B0")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.lineEdit_B_B0)
        self.lineEdit_B_B1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_B_B1.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_B_B1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_B_B1.setObjectName("lineEdit_B_B1")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineEdit_B_B1)
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.label_29)
        self.lineEdit_B_B2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_B_B2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_B_B2.setObjectName("lineEdit_B_B2")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.lineEdit_B_B2)
        self.lineEdit_B_B3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_B_B3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_B_B3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_B_B3.setObjectName("lineEdit_B_B3")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineEdit_B_B3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(16, QtWidgets.QFormLayout.LabelRole, spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(16, QtWidgets.QFormLayout.FieldRole, spacerItem11)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(50, 30))
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_C_A = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_C_A.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_C_A.setObjectName("lineEdit_C_A")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_C_A)
        self.lineEdit_C_A0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_C_A0.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_C_A0.setMaximumSize(QtCore.QSize(150, 30))
        self.lineEdit_C_A0.setObjectName("lineEdit_C_A0")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lineEdit_C_A0)
        self.lineEdit_C_A1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_C_A1.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_C_A1.setObjectName("lineEdit_C_A1")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_C_A1)
        self.lineEdit_C_A2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_C_A2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_C_A2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_C_A2.setObjectName("lineEdit_C_A2")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lineEdit_C_A2)
        self.lineEdit_C_A3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_C_A3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_C_A3.setObjectName("lineEdit_C_A3")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_C_A3)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(50, 30))
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_C_B0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_C_B0.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_C_B0.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_C_B0.setObjectName("lineEdit_C_B0")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.lineEdit_C_B0)
        self.lineEdit_C_B1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_C_B1.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_C_B1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_C_B1.setObjectName("lineEdit_C_B1")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineEdit_C_B1)
        self.lineEdit_C_B2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_C_B2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_C_B2.setObjectName("lineEdit_C_B2")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.lineEdit_C_B2)
        self.lineEdit_C_B3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_C_B3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_C_B3.setObjectName("lineEdit_C_B3")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.lineEdit_C_B3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(15, QtWidgets.QFormLayout.LabelRole, spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(15, QtWidgets.QFormLayout.FieldRole, spacerItem16)
        self.lineEdit_C_B = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_C_B.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_C_B.setObjectName("lineEdit_C_B")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_C_B)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem17)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_58 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_58.setObjectName("label_58")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_58)
        self.label_59 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_59.setObjectName("label_59")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_59)
        self.label_60 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_60.setObjectName("label_60")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_60)
        self.label_61 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_61.setObjectName("label_61")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_61)
        self.label_62 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_62.setObjectName("label_62")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_62)
        self.label_63 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_63.setObjectName("label_63")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.label_63)
        self.label_64 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_64.setObjectName("label_64")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.label_65 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_65.setObjectName("label_65")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.label_65)
        self.label_66 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_66.setObjectName("label_66")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_66)
        self.label_67 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_67.setObjectName("label_67")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.label_67)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "拉伸机同轴度测量系统"))
        self.label.setText(_translate("Form", "COM"))
        self.btnSetParameters.setText(_translate("Form", "设置参数"))
        self.btn_delete_force.setText(_translate("Form", "删除"))
        self.btn_apply_force.setStatusTip(_translate("Form", "开始前先点击应用"))
        self.btn_apply_force.setText(_translate("Form", "应用"))
        self.btn_add_force.setText(_translate("Form", "添加"))
        self.btnEnd.setText(_translate("Form", "结束测量"))
        self.btnReceive.setText(_translate("Form", "开始测量"))
        self.btnSave.setText(_translate("Form", "保存数据"))
        self.checkBox_twice.setText(_translate("Form", "两次测量"))
        self.widget_strain.setWhatsThis(_translate("Form", "<html><head/><body><p>开始测量过程前先点击应用确认测量数据</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "实时显示"))
        self.label_2.setText(_translate("Form", "A面"))
        self.label_3.setText(_translate("Form", "轴向应变"))
        self.label_4.setText(_translate("Form", "弯曲应变"))
        self.label_11.setText(_translate("Form", "1"))
        self.label_12.setText(_translate("Form", "2"))
        self.label_13.setText(_translate("Form", "3"))
        self.label_14.setText(_translate("Form", "4"))
        self.label_15.setText(_translate("Form", "平均值"))
        self.label_16.setText(_translate("Form", "1"))
        self.label_17.setText(_translate("Form", "2"))
        self.label_18.setText(_translate("Form", "3"))
        self.label_19.setText(_translate("Form", "4"))
        self.label_68.setText(_translate("Form", "平均值"))
        self.label_5.setText(_translate("Form", "B面"))
        self.label_20.setText(_translate("Form", "平均值"))
        self.label_6.setText(_translate("Form", "轴向应变"))
        self.label_21.setText(_translate("Form", "1"))
        self.label_22.setText(_translate("Form", "2"))
        self.label_23.setText(_translate("Form", "3"))
        self.label_24.setText(_translate("Form", "4"))
        self.label_25.setText(_translate("Form", "平均值"))
        self.label_7.setText(_translate("Form", "弯曲应变"))
        self.label_26.setText(_translate("Form", "1"))
        self.label_27.setText(_translate("Form", "2"))
        self.label_28.setText(_translate("Form", "3"))
        self.label_29.setText(_translate("Form", "4"))
        self.label_9.setText(_translate("Form", "轴向应变"))
        self.label_10.setText(_translate("Form", "弯曲应变"))
        self.label_8.setText(_translate("Form", "C面"))
        self.label_58.setText(_translate("Form", "平均值"))
        self.label_59.setText(_translate("Form", "1"))
        self.label_60.setText(_translate("Form", "2"))
        self.label_61.setText(_translate("Form", "3"))
        self.label_62.setText(_translate("Form", "4"))
        self.label_63.setText(_translate("Form", "平均值"))
        self.label_64.setText(_translate("Form", "1"))
        self.label_65.setText(_translate("Form", "2"))
        self.label_66.setText(_translate("Form", "3"))
        self.label_67.setText(_translate("Form", "4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "测量值"))

from strainplotwidget import StrainPlotWidget
