# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TZD.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1332, 652)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 321, 511))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(-1, -1, 0, 10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableView_force = QtWidgets.QTableView(self.gridLayoutWidget_4)
        self.tableView_force.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tableView_force.setObjectName("tableView_force")
        self.gridLayout_4.addWidget(self.tableView_force, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.btnSetParameters = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnSetParameters.setObjectName("btnSetParameters")
        self.horizontalLayout.addWidget(self.btnSetParameters)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_delete_force = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_delete_force.setObjectName("btn_delete_force")
        self.gridLayout_3.addWidget(self.btn_delete_force, 0, 1, 1, 1)
        self.btn_apply_force = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_apply_force.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.btn_apply_force.setObjectName("btn_apply_force")
        self.gridLayout_3.addWidget(self.btn_apply_force, 1, 0, 1, 1)
        self.btn_add_force = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_add_force.setObjectName("btn_add_force")
        self.gridLayout_3.addWidget(self.btn_add_force, 0, 0, 1, 1)
        self.btnEnd = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnEnd.setObjectName("btnEnd")
        self.gridLayout_3.addWidget(self.btnEnd, 1, 2, 1, 1)
        self.btnReceive = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnReceive.setObjectName("btnReceive")
        self.gridLayout_3.addWidget(self.btnReceive, 0, 2, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout_3.addWidget(self.btnSave, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.textBrowser_info = QtWidgets.QTextBrowser(Form)
        self.textBrowser_info.setGeometry(QtCore.QRect(20, 550, 1281, 71))
        self.textBrowser_info.setObjectName("textBrowser_info")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(366, 9, 951, 531))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget_strain = StrainPlotWidget(self.tab)
        self.widget_strain.setGeometry(QtCore.QRect(10, 0, 931, 491))
        self.widget_strain.setMinimumSize(QtCore.QSize(800, 0))
        self.widget_strain.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.widget_strain.setObjectName("widget_strain")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 921, 361))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 30))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(50, 30))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_A_A = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_A.setObjectName("lineEdit_A_A")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_A)
        self.lineEdit_A_A0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A0.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A0.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_A_A0.setObjectName("lineEdit_A_A0")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_A0)
        self.lineEdit_A_A1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A1.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_A1.setObjectName("lineEdit_A_A1")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_A1)
        self.lineEdit_A_A2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_A_A2.setObjectName("lineEdit_A_A2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_A2)
        self.lineEdit_A_A3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_A3.setObjectName("lineEdit_A_A3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_A3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(50, 30))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_A_B = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_B.setObjectName("lineEdit_A_B")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_B)
        self.lineEdit_A_B0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B0.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B0.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_A_B0.setObjectName("lineEdit_A_B0")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_B0)
        self.lineEdit_A_B1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B1.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_B1.setObjectName("lineEdit_A_B1")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_B1)
        self.lineEdit_A_B2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B2.setObjectName("lineEdit_A_B2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_B2)
        self.lineEdit_A_B3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_B3.setObjectName("lineEdit_A_B3")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_B3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(50, 30))
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(50, 30))
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_A_A_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_A_2.setObjectName("lineEdit_A_A_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_A_2)
        self.lineEdit_A_A0_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A0_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A0_2.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_A_A0_2.setObjectName("lineEdit_A_A0_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_A0_2)
        self.lineEdit_A_A1_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A1_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A1_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_A1_2.setObjectName("lineEdit_A_A1_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_A1_2)
        self.lineEdit_A_A2_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A2_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A2_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_A_A2_2.setObjectName("lineEdit_A_A2_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_A2_2)
        self.lineEdit_A_A3_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A3_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A3_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_A3_2.setObjectName("lineEdit_A_A3_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_A3_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem9)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(50, 30))
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_A_B_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_B_2.setObjectName("lineEdit_A_B_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_B_2)
        self.lineEdit_A_B0_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B0_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B0_2.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_A_B0_2.setObjectName("lineEdit_A_B0_2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_B0_2)
        self.lineEdit_A_B1_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B1_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B1_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_B1_2.setObjectName("lineEdit_A_B1_2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_B1_2)
        self.lineEdit_A_B2_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B2_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B2_2.setObjectName("lineEdit_A_B2_2")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_B2_2)
        self.lineEdit_A_B3_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B3_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B3_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_B3_2.setObjectName("lineEdit_A_B3_2")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_B3_2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(10, QtWidgets.QFormLayout.FieldRole, spacerItem11)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(50, 30))
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_A_A_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A_3.setObjectName("lineEdit_A_A_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_A_3)
        self.lineEdit_A_A0_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A0_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A0_3.setMaximumSize(QtCore.QSize(150, 30))
        self.lineEdit_A_A0_3.setObjectName("lineEdit_A_A0_3")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_A0_3)
        self.lineEdit_A_A1_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A1_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A1_3.setObjectName("lineEdit_A_A1_3")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_A1_3)
        self.lineEdit_A_A2_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A2_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A2_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_A_A2_3.setObjectName("lineEdit_A_A2_3")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_A2_3)
        self.lineEdit_A_A3_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_A3_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_A3_3.setObjectName("lineEdit_A_A3_3")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_A3_3)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(50, 30))
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_A_B0_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B0_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B0_3.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_A_B0_3.setObjectName("lineEdit_A_B0_3")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_B0_3)
        self.lineEdit_A_B1_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B1_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B1_3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_A_B1_3.setObjectName("lineEdit_A_B1_3")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_B1_3)
        self.lineEdit_A_B2_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B2_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B2_3.setObjectName("lineEdit_A_B2_3")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lineEdit_A_B2_3)
        self.lineEdit_A_B3_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B3_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B3_3.setObjectName("lineEdit_A_B3_3")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_B3_3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(10, QtWidgets.QFormLayout.FieldRole, spacerItem16)
        self.lineEdit_A_B_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_A_B_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_A_B_3.setObjectName("lineEdit_A_B_3")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A_B_3)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem17)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(50, 30))
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.horizontalLayoutWidget.raise_()
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "拉伸机同轴度测量系统"))
        self.label.setText(_translate("Form", "COM"))
        self.btnSetParameters.setText(_translate("Form", "设置参数"))
        self.btn_delete_force.setText(_translate("Form", "删除"))
        self.btn_apply_force.setStatusTip(_translate("Form", "开始前先点击应用"))
        self.btn_apply_force.setText(_translate("Form", "应用"))
        self.btn_add_force.setText(_translate("Form", "添加"))
        self.btnEnd.setText(_translate("Form", "结束测量"))
        self.btnReceive.setText(_translate("Form", "开始测量"))
        self.btnSave.setText(_translate("Form", "保存数据"))
        self.widget_strain.setWhatsThis(_translate("Form", "<html><head/><body><p>开始测量过程前先点击应用确认测量数据</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "实时显示"))
        self.label_2.setText(_translate("Form", "A面"))
        self.label_3.setText(_translate("Form", "轴向应变"))
        self.label_4.setText(_translate("Form", "弯曲应变"))
        self.label_5.setText(_translate("Form", "A面"))
        self.label_6.setText(_translate("Form", "轴向应变"))
        self.label_7.setText(_translate("Form", "弯曲应变"))
        self.label_9.setText(_translate("Form", "轴向应变"))
        self.label_10.setText(_translate("Form", "弯曲应变"))
        self.label_8.setText(_translate("Form", "A面"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "测量值"))

from strainplotwidget import StrainPlotWidget
